artifacts_root: artifacts

data_ingestion:
root_dir: artifacts/data_ingestion
source_url: https://github.com/thekazisakib/E2E-ML-Project-/raw/main/wine.zip
local_datafile: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion